"""Compile saved lab recipes to native descriptors/LUTs; emit an apply_patch."""
import json
from pathlib import Path

import numpy as np

from surface_colour_engine import gradient

root = Path(__file__).resolve().parents[1]
palettes = {}
programs = []
for number in range(13, 21):
    recipe = json.loads((root / f"scripts/fixtures/surface-colour-lab/program-{number}.json").read_text())
    base, detail = recipe["layers"]
    assert recipe["space"] == "oklab"
    assert recipe["input"] == "peak"
    assert base["enabled"] and detail["enabled"]
    assert base["mask"] == "none"
    assert base.get("colour_source", "filtered") == "filtered"
    assert base["filter"] == "raw" and detail["axis"] == "y"
    assert base["blend"] == "normal" and detail["blend"] == "screen"
    assert base["opacity"] == detail["opacity"] == 1
    assert detail["mask"] == "amplitude" and detail.get("colour_source", "filtered") == "filtered"
    ids = []
    for layer in (base, detail):
        key = json.dumps(layer["stops"], sort_keys=True)
        if key not in palettes:
            palettes[key] = (len(palettes), gradient(np.linspace(0, 1, 2049), layer["stops"], "oklab"))
        ids.append(palettes[key][0])
    inner = detail["sigma"] if detail["filter"] == "bandpass" else 0
    outer = detail["outer"] if detail["filter"] == "bandpass" else detail["sigma"]
    programs.append([*ids, inner, outer, base["gain"], base["offset"],
                     detail["gain"], detail["offset"], detail["alpha_boost"]])

lines = ["#pragma once", "", "// Generated by scripts/compile_surface_programs.py; lab OKLab -> linear RGB.",
         "#include <array>", "", "namespace SurfaceProgramData {",
         "using Palette = std::array<std::array<float, 3>, 2049>;", ""]
for index, colours in palettes.values():
    lines.append(f"inline constexpr Palette palette{index} {{{{")
    for colour in colours:
        lines.append("    {{ " + ", ".join(f"{float(c):.9e}f" for c in colour) + " }},")
    lines.extend(["}};", ""])
lines.extend(["struct Program {", "    const Palette& base;", "    const Palette& detail;",
              "    float innerSigma;", "    float outerSigma;", "    float baseGain;",
              "    float baseOffset;", "    float detailGain;", "    float detailOffset;",
              "    float alphaBoost;", "};", "", "inline constexpr std::array<Program, 8> programs {{"])
for base, detail, *params in programs:
    lines.append(f"    {{ palette{base}, palette{detail}, " + ", ".join(f"{float(p):.9e}f" for p in params) + " },")
lines.extend(["}};", "}"])
target = root / "lib/src/UI/Panels/SurfaceProgramPalette.h"
print("*** Begin Patch")
if target.exists():
    print("*** Update File: " + str(target) + "\n@@")
    print("\n".join("-" + line for line in target.read_text().splitlines()))
else:
    print("*** Add File: " + str(target))
print("\n".join("+" + line for line in lines))
print("*** End Patch")
