"""Emit an apply_patch adding the compiled recipe palette header (no runtime Python)."""
import json
from pathlib import Path

import numpy as np

from surface_colour_engine import gradient

root = Path(__file__).resolve().parents[1]
recipe = json.loads((root / "scripts/fixtures/surface-colour-lab/program-13.json").read_text())
other = json.loads((root / "scripts/fixtures/surface-colour-lab/program-14.json").read_text())
assert recipe["layers"][1]["stops"] == other["layers"][1]["stops"]
assert recipe["space"] == other["space"] == "oklab"
colours = gradient(np.linspace(0, 1, 2049), recipe["layers"][1]["stops"], recipe["space"])
lines = ["#pragma once", "", "// Generated by scripts/compile_surface_programs.py using the lab's OKLab evaluator.",
         "#include <array>", "", "namespace SurfaceProgramData {",
         "inline constexpr std::array<std::array<float, 3>, 2049> icyHot {{"]
for colour in colours:
    lines.append("    {{ " + ", ".join(f"{float(c):.9e}f" for c in colour) + " }},")
lines.extend(["}};", "}"])
print("*** Begin Patch\n*** Add File: " + str(root / "lib/src/UI/Panels/SurfaceProgramPalette.h"))
print("\n".join("+" + line for line in lines))
print("*** End Patch")
